# Generated by Django 3.2.10 on 2022-06-23 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0018_auto_20220114_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('qrcode_count', models.IntegerField(default=0, verbose_name='QR Code Count')),
                ('qrcode_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)')),
                ('qrcode_is_paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessUser', to=settings.AUTH_USER_MODEL, verbose_name='Business User')),
            ],
            options={
                'verbose_name': 'QR Code Invoice',
                'verbose_name_plural': 'QR Code Invoices',
            },
        ),
    ]
